version: "3"
services:
  db:
    container_name: postgres-14.2
    image: postgres:14.2
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: password
    restart: always
  web:
    container_name: spring-boot-template
    build: .
    ports:
      - 8088:8088
    depends_on:
      - db